#!/bin/bash

mydir="`dirname $0`"

android_jar=$mydir/jdk-android.jar
echo "Using $android_jar..."
androidOpts=" -force-android-jar $android_jar -ire -src-prec apk -allow-phantom-refs"
#androidOpts=" -android-jars /projects/proganalysis/Software/android-sdk-linux/platforms -ire -src-prec apk "                           #androidOpts=" -android-jars $mydir/../jdk/android/platforms -ire -src-prec apk "                                                      

$mydir/soot-sflow-java $@ $androidOpts
