#!/bin/bash 

#command:
#sh mapreduce -cp ../tests -main sample.Sample -d ../output/sample

start=`date +%s`

mydir="`dirname $0`"
mrlib=`find $mydir/../benchmarks/mapreduce/lib -name '*.jar' | xargs | sed 's/ /:/g'`
soot=$mydir/../lib/soot-trunk.jar
inference=$mydir/../lib/soot-inference.jar:$mydir/../lib/jars/annotations-2.0.1.jar:$mydir/../lib/encryption.jar:$mydir/../lib/jars/api-all-1.0.0-m20.jar
jdk=$mydir/../jdk/reim/jdk.jar
rt8=$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/jre/lib/jce.jar

classpath="$mrlib:$inference:$rt8"
outputDir=""
appMainClass=""
appClassPath=""
phase=""
while [[ $# > 0 ]]
do
  key=$1
  shift
  case $key in
    -main ) appMainClass=$appMainClass"`echo $1`"
    shift
    ;;
    -cp ) appClassPath=$appClassPath"`echo $1`"
    shift
    ;;
    -d ) outputDir=$outputDir"`echo $1`"
    ;;
    -phase ) phase=$phase"`echo $1`"
  esac
done

mkdir -p $outputDir

if [[ $phase == *"1"* ]]
then
echo
echo "-------- Phase 1: Build Source --------"
echo
find $appClassPath -name '*.java' | xargs javac -cp $mrlib:$appClassPath:$inference -d $outputDir
fi

if [[ $phase == *"2"* ]]
then
mainClass="edu.rpi.SootInferenceJCrypt"

echo
echo "-------- Phase 2: Type Inference --------"
echo
java -cp $inference:$soot $mainClass -cp $outputDir:$classpath -process-dir $outputDir -f jimple -d $outputDir
fi

if [[ $phase == *"3"* ]]
then

mainClass="edu.rpi.TranslatorMain"

echo
echo "-------- Phase 3: Code Generation --------"
echo
java -cp $inference:$soot $mainClass -cp $outputDir:$classpath -pp -process-dir $outputDir -d $outputDir
fi

if [[ $phase == *"4"* ]]
then

mainClass="edu.rpi.SootInferenceJCrypt"

echo
echo "-------- Phase 4: Type Inference 2 --------"
echo
java -cp $inference:$soot $mainClass -allow-phantom-refs -cp $outputDir:$classpath -pp -process-dir $outputDir -f none -d $outputDir
fi

if [[ $phase == *"5"* ]]
then

mainClass="vasco.soot.examples.JCryptMain"

echo
echo "-------- Phase 5: AE Analysis --------"
echo
for className in `find $outputDir -name '*.class'`
do
    className=${className#$outputDir/}
    className=${className%.*}
    appMC=${className//\//\.}
    echo "Analyzing $appMC ..."
    java -cp $inference:$soot $mainClass -cp $outputDir -d $outputDir -MR $appMC
done
fi

end=`date +%s`

echo "Total Time is $((end-start)) s."