#!/bin/bash 

#command:
#sh soot-jcrypt -cp ../tests -main sample.Sample -d ../sootOutput/sample

mydir="`dirname $0`"
mylib=`find $mydir/../lib -name '*.jar' | xargs |sed 's/ /:/g'`
jdk=$mydir/../jdk/reim/jdk.jar
rt=$JAVA_HOME/jre/lib/rt.jar

mainClass="edu.rpi.SootInferenceJCrypt"

sootClasspath="$mylib:$jdk:$rt"
outputDir=""
appMainClass=""
while [[ $# > 0 ]]
do
  key=$1
  shift
  case $key in
    -main ) appMainClass=$appMainClass"`echo $1`"
    shift
    ;;
    -cp ) sootClasspath=$sootClasspath:"`echo $1`"
    shift
    ;;
    -d ) outputDir=$outputDir" `echo $1`"" "
  esac
done
                                                          
echo "java -cp $mylib $mainClass -cp $sootClasspath $outputDir $appMainClass"

java -cp $mylib $mainClass -cp $sootClasspath -d $outputDir $appMainClass
