#!/bin/bash 

#command:
#sh soot-jcrypt -cp ../tests -main sample.Sample -d ../output/sample

start=`date +%s`

mydir="`dirname $0`"
mylib=`find $mydir/../lib -name '*.jar' | xargs |sed 's/ /:/g'`
jdk=$mydir/../jdk/reim/jdk.jar
rt=$JAVA_HOME/jre/lib/rt.jar
#rt6=/Users/yaodong/Software/jdk1.6.0_27/jre/lib/rt.jar

mainClass="edu.rpi.SootInferenceJCrypt"

sootClasspath="$mylib:$jdk:$rt"
outputDir=""
appMainClass=""
while [[ $# > 0 ]]
do
  key=$1
  shift
  case $key in
    -main ) appMainClass=$appMainClass"`echo $1`"
    shift
    ;;
    -cp ) sootClasspath=$sootClasspath:"`echo $1`"
    shift
    ;;
    -d ) outputDir=$outputDir"`echo $1`"
  esac
done

echo
echo "-------- Phase 1: Type Inference --------"
echo
echo "java -cp $mylib $mainClass -cp $sootClasspath -d $outputDir $appMainClass"

java -cp $mylib $mainClass -cp $sootClasspath -d $outputDir $appMainClass

mainClass="edu.rpi.TranslatorMain"

echo
echo "-------- Code Generation --------"
echo
echo "java -cp $mylib $mainClass -cp $sootClasspath -d $outputDir $appMainClass"

#java -cp $mylib $mainClass -cp $sootClasspath -d $outputDir $appMainClass

mainClass="vasco.soot.examples.JCryptMain"

echo
echo "-------- Phase 2: AE Analysis --------"
echo
echo "java -Xss50m -Xmx2048m -XX:-UseConcMarkSweepGC -cp $mylib $mainClass -cp $outputDir -d $outputDir $appMainClass"

#java -Xss50m -Xmx2048m -XX:-UseConcMarkSweepGC -cp $mylib $mainClass -cp $outputDir -d $outputDir $appMainClass > $outputDir/conversion-result.txt

end=`date +%s`

echo "Total Time is $((end-start)) s."