#!/bin/bash

mydir="`dirname $0`"
mylib=`find $mydir/ -name *.jar | xargs |sed 's/ /:/g'`
jdk=$mydir/jdk-android.jar
rt="/projects/proganalysis/Software/jdk1.6.0_27/jre/lib/rt.jar"

mainClass="edu.rpi.SootInference"
javaOpts=" -DpolyLibrary -DinferAndroidApp "
android_jar=$jdk
androidOpts=" -force-android-jar $android_jar -ire -src-prec apk "
cpOpts="$mylib:$jdk:$rt:"
toolOpts=""

while [[ $# > 0 ]]
do
  key=$1
  shift
  case $key in 
    -D* ) javaOpts=$javaOpts"`echo $key`"" "
    ;;
    -cp ) cpOpts=$cpOpts:"`echo $1`"" "
    shift
    ;;
    * ) toolOpts=$toolOpts"`echo $key`"" "
  esac
done

echo "java -Xss50m -Xmx1500m $javaOpts -classpath $cpOpts $mainClass $androidOpts \
  -process-dir $toolOpts --soot-classpath $cpOpts"

jdb -sourcepath $mydir/../src:/projects/proganalysis/SOOT-Nightly/soot-github/src \
  -Xss50m -Xmx1500m $javaOpts -classpath $cpOpts $mainClass $androidOpts \
  -process-dir $toolOpts --soot-classpath $cpOpts

